name: bad_project
on:
  push:
    branches:
      - '*'
  workflow_dispatch:

env:
  POSTGRES_DB: fungi
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST: postgres

jobs:
  testing:
    runs-on: ubuntu-latest
    container: node:latest
    services:
      postgres:
        image: postgres
        env: 
          POSTGRES_DB: ${{env.POSTGRES_DB}}
          POSTGRES_PASSWORD: ${{env.POSTGRES_PASSWORD}}
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - run: |
          yarn install 
          yarn knex migrate:latest --env test
          cd test
          yarn jest ./hash.test.ts
        working-directory: ./
  deploy:
      if: github.ref_name == 'production'
      runs-on: ubuntu-latest
      needs: testing
      steps:
      - name: ssh to pull latest version
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd hk-map-22-aug-22-sw-exercises-solution/03_BAD/BAD005/memo_wall
            git pull origin main
            yarn install
            yarn knex migrate:latest --env production
            forever restart index.js
          host: c22sw.tecky.dev
          user: ubuntu
          key: ${{secrets.SSH_PRIVATE_KEY}}